[workspace]
members = [
    "rust/aes-gcm-siv",
    "rust/protocol",
    "rust/bridge/ffi",
    "rust/bridge/jni",
    "rust/bridge/node",
]
default-members = [
    "rust/aes-gcm-siv",
    "rust/protocol",
]
